version: '3.7'

services:
  postgres:
    container_name: spring-api-db
    image: mysql:8.3
    #    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpw}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-basic}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --log-error-verbosity=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_lock_wait_timeout=1
    ports:
      - "3307:3306"
    restart: always
    #    healthcheck:
    #      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
    #      interval: 3s
    #      retries: 5
    #      start_period: 30s
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.